[package]
name = "rust_renderer"
version = "0.1.0"
build = "build.rs"
authors = ["Spr00t"]

[dependencies]
log = "0.3"
libc = "*"
rand = "*"
env_logger = "0.3"

[build-dependencies]
gcc = "0.3"
pkg-config = "^0.3.8"
